version: '3.8'

services:
  bot:
    container_name: telegram_bot
    build: .
    volumes:
      - bot_data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=/app/data/monitoring.db
    restart: unless-stopped

volumes:
  bot_data:
    name: telegram_bot_data
