version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bot_data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=/app/data/monitoring.db
      - CHECK_INTERVAL=300
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; os.path.exists('/app/data/monitoring.db')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  bot_data:
    driver: local